export const baseSchemas = {
  seedream: {
    id: 'seedream',
    name: 'Seedream Image',
    description: 'Seedream images/generations request schema (API 1:1).',
    fields: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        options: [
            // Seedream Models
            'seedream-5-0-lite',
            'seedream-4-5-251128', 
            'seedream-4-0-250828', 
            'seedream-5-0-260128',
            'seedream-3-0-t2i',
            'seededit-3-0-i2i',
            // Seedance Models (Added for unified dropdown)
            'seedance-1-5-pro-251215',
            'seedance-1-0-pro',
            'seedance-pro-fast',
            'seedance-1-0-lite-t2v',
            'seedance-1-0-lite-i2v'
        ],
        defaultValue: 'seedream-5-0-lite',
        description: 'Select a model (Image or Video).',
      },
      {
        key: 'prompt',
        label: 'Prompt',
        type: 'text',
        required: true,
        description: 'Primary text prompt. Max ~600 words.',
      },
      // ... (rest of fields will be dynamically hidden/shown)
      {
        key: 'image',
        label: 'Reference Images (Seedream)',
        type: 'image-list',
        description: 'Optional reference images (URL or Base64). Up to 14 images for multi-image blending.',
      },
      {
        key: 'size',
        label: 'Size (Image)',
        type: 'enum',
        options: ['2K', '4K', 'Custom'],
        defaultValue: '2K',
        description: 'Output resolution. 2K=2048x2048 approx. Custom allows specific WxH.',
      },
      {
        key: 'width',
        label: 'Width (px)',
        type: 'number',
        hidden: true,
        description: 'Custom width in pixels.',
      },
      {
        key: 'height',
        label: 'Height (px)',
        type: 'number',
        hidden: true,
        description: 'Custom height in pixels.',
      },
      {
        key: 'watermark',
        label: 'Watermark',
        type: 'boolean',
        defaultValue: false,
        description: 'Whether to apply a watermark to the output.',
      },
      {
        key: 'sequential_image_generation',
        label: 'Sequential Generation (Image)',
        type: 'boolean',
        defaultValue: false,
        description: 'Generate multiple related images in sequence (auto).',
      },
      {
        key: 'sequential_max_images',
        label: 'Max Images (Batch)',
        type: 'number',
        defaultValue: 5,
        hidden: true, 
        description: 'Max images to generate (1-15). Only for sequential generation.',
      },
      {
        key: 'optimize_prompt_mode',
        label: 'Optimize Prompt Mode (Image)',
        type: 'enum',
        options: ['standard', 'fast'],
        defaultValue: 'standard',
        description: 'Prompt optimization mode (Standard/Fast).',
      },
      {
        key: 'output_format',
        label: 'Output Format (Image)',
        type: 'enum',
        options: ['jpeg', 'png'],
        defaultValue: 'jpeg',
        description: 'Output image format (5.0-lite only).',
      },
      {
        key: 'guidance_scale',
        label: 'Guidance Scale (3.0)',
        type: 'number',
        defaultValue: 2.5,
        description: 'Controls prompt adherence (1-10). Only for 3.0 models.',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'number',
        defaultValue: -1,
        description: 'Random seed (-1 for random).',
      },
      {
        key: 'response_format',
        label: 'Response Format (Image)',
        type: 'enum',
        options: ['url', 'b64_json'],
        defaultValue: 'url',
        description: 'Output format for the generated image.',
      },
      // Seedance specific fields
      {
        key: 'first_frame',
        label: 'First Frame Image (Video)',
        type: 'image-list',
        description: 'First frame image for Image-to-Video generation (Single image).',
      },
      {
        key: 'last_frame',
        label: 'Last Frame Image (Video)',
        type: 'image-list',
        description: 'Last frame image for First-and-Last-Frame generation (Single image).',
      },
      {
        key: 'reference_images',
        label: 'Reference Images (Video)',
        type: 'image-list',
        description: 'Reference images (1-4) for Seedance 1.0 Lite I2V.',
      },
      {
        key: 'resolution',
        label: 'Resolution (Video)',
        type: 'enum',
        options: ['480p', '720p', '1080p'],
        defaultValue: '720p',
        description: 'Resolution of the output video.',
      },
      {
        key: 'ratio',
        label: 'Aspect Ratio (Video)',
        type: 'enum',
        options: ['16:9', '4:3', '1:1', '3:4', '9:16', '21:9', 'adaptive'],
        defaultValue: '16:9',
        description: 'Aspect ratio of the output video.',
      },
      {
        key: 'duration',
        label: 'Duration (Video)',
        type: 'number',
        defaultValue: 5,
        description: 'Video duration in seconds (2-12s). -1 for auto (1.5 pro only).',
      },
      {
        key: 'generate_audio',
        label: 'Generate Audio (Video)',
        type: 'boolean',
        defaultValue: true,
        description: 'Generate synchronized audio (1.5 pro only).',
      },
      {
        key: 'camera_fixed',
        label: 'Fix Camera (Video)',
        type: 'boolean',
        defaultValue: false,
        description: 'Attempt to keep camera fixed.',
      },
    ],
    defaults: {
      model: 'seedream-5-0-lite',
      prompt: 'A hero product shot of a premium skincare bottle on a minimal studio set.',
      size: '2K',
      width: 2048,
      height: 2048,
      image: [],
      watermark: false,
      sequential_image_generation: false,
      sequential_max_images: 5,
      optimize_prompt_mode: 'standard',
      output_format: 'jpeg',
      guidance_scale: 2.5,
      seed: -1,
      response_format: 'url',
      // Seedance defaults
      first_frame: [],
      last_frame: [],
      reference_images: [],
      resolution: '720p',
      ratio: '16:9',
      duration: 5,
      generate_audio: true,
      camera_fixed: false,
    },
  },
  // Removed separate 'seedance' key since we are unifying into one main UI
};

export const apiKeyStorageKey = 'modelark_api_key';
