// The Timeline + Bible — pure, substrate-free helpers. No React, no canvas, no
// network. Shared by projectShape (defaults/migration), FilmCanvas (mirroring a
// production session onto the spine) and StoryTimeline (rendering it).
//
// The timeline is the fundamental layer: an ordered set of events, each a chunk of
// the film (a keyframe still that gets animated into a clip). The bible is the
// global, atemporal layer — style, characters, locations, props, brand assets —
// that every tool references so chunks stay consistent. The time axis gives every
// generation a coordinate; the bible gives every generation its shared identity.

let _seq = 0;
const uid = (p) => `${p}-${Date.now().toString(36)}-${(_seq += 1).toString(36)}`;

export const BIBLE_ROLES = ['style', 'character', 'location', 'prop', 'brand'];

// How many bible references a single chunk receives. Bounded so the image model
// isn't swamped; style/brand lead because they set the look every shot shares.
export const BIBLE_REF_CAP = 4;
// When the user curated a shot's references EXPLICITLY (CUT cards), their selection
// wins up to the model's actual limit — Seedream accepts up to 9 reference images.
export const EXPLICIT_REF_CAP = 9;
export const DEFAULT_EVENT_SECONDS = 5;
// A fresh timeline targets 15s — a short clip / ad length — the common first cut.
// It's just a budget marker; the spine grows past it (shown over-budget) freely.
export const DEFAULT_TIMELINE_SECONDS = 15;

// Status of an event as it moves through the funnel.
export const EVENT_STATUS = ['empty', 'keyframe', 'rendering', 'shot', 'failed'];

export const emptyBible = () => ({ entries: [] });

export const emptyTimeline = (targetSeconds = DEFAULT_TIMELINE_SECONDS) => ({
  targetSeconds: Math.round(Number(targetSeconds) || DEFAULT_TIMELINE_SECONDS),
  events: [],
  film: null, // { url, assetId, builtAt }
});

export const bibleEntry = ({
  id, role = 'style', name = '', url = '', nodeId = null, locked = true,
} = {}) => ({
  id: id || uid('bib'),
  // Accept any role string — generic (style/character/…) AND recipe roles
  // (product/talent/look/brand…). It's a tag; unknown roles render with a fallback.
  role: role || 'style',
  name: name || role,
  url: url || '',
  nodeId: nodeId || null,
  // Bible entries are canonical anchors → locked by default; locked entries are
  // never regenerated by an iteration or auto-run.
  locked: locked !== false,
});

export const timelineEvent = ({
  id, order = 0, beat = '', durationSec = DEFAULT_EVENT_SECONDS,
  keyframeUrl = '', keyframeNodeId = null, shotUrl = '', shotNodeId = null,
  bibleRefs = [], status = 'empty', locked = false, feedback = '',
  stepId = null, qc = null,
} = {}) => ({
  id: id || uid('ev'),
  order,
  beat: beat || '',
  durationSec: Number(durationSec) > 0 ? Number(durationSec) : DEFAULT_EVENT_SECONDS,
  keyframeUrl: keyframeUrl || '',
  keyframeNodeId: keyframeNodeId || null,
  shotUrl: shotUrl || '',
  shotNodeId: shotNodeId || null,
  bibleRefs: Array.isArray(bibleRefs) ? bibleRefs.filter(Boolean) : [],
  status: EVENT_STATUS.includes(status) ? status : 'empty',
  locked: !!locked,
  feedback: feedback || '',
  // Links the event to its production animate step (when engine-driven). Manual
  // events (Add to timeline, migrated story beats) have no stepId.
  stepId: stepId || null,
  qc: qc || null,
});

// Events ordered for playback / stitch (explicit order, stable).
export const orderedEvents = (events = []) =>
  [...(events || [])].sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

export const totalDuration = (events = []) =>
  orderedEvents(events).reduce((sum, e) => sum + (Number(e.durationSec) || 0), 0);

// Reassign order to match array position (after a reorder / mirror).
export const renumber = (events = []) => events.map((e, i) => ({ ...e, order: i }));

// Resolve bible-entry ids → reference image URLs, style/brand first, capped. This
// is the mechanism every tool uses to stay consistent: each chunk is generated
// WITH the look + identities it must honor. Dedupes; skips entries with no url.
export const resolveBibleUrls = (refIds, bibleEntries = [], cap = BIBLE_REF_CAP) => {
  if (!refIds || !refIds.length || !bibleEntries || !bibleEntries.length) return [];
  const byId = new Map(bibleEntries.map((e) => [e.id, e]));
  const weight = (r) => (r.role === 'style' || r.role === 'brand' ? 0 : 1);
  const seen = new Set();
  const out = [];
  refIds
    .map((id) => byId.get(id))
    .filter(Boolean)
    .sort((a, b) => weight(a) - weight(b))
    .forEach((e) => {
      if (e.url && !seen.has(e.url)) { seen.add(e.url); out.push(e.url); }
    });
  return out.slice(0, cap);
};

// ---- mirroring a production session onto the spine ----------------------------

const pickedOutput = (step) => {
  if (!step) return null;
  const outs = step.outputs || [];
  return outs.find((o) => o.id === step.pickedId) || outs[0] || null;
};

// Map a production snapshot's `animate` steps → timeline events (the shots, in plan
// order). Human-owned fields (durationSec, locked, feedback, manual keyframe) are
// preserved from the previous event keyed by step id; engine fields (keyframeUrl,
// shotUrl, status, beat, bibleRefs, qc) are refreshed from the session. Manual
// (non-step) events are kept and appended after the engine shots.
export const mirrorSessionEvents = (state, prevEvents = []) => {
  const plan = (state && state.plan) || [];
  const planStepIds = new Set(plan.map((s) => s.id));
  const prevByStep = new Map((prevEvents || []).filter((e) => e.stepId).map((e) => [e.stepId, e]));
  const stepById = new Map(plan.map((s) => [s.id, s]));

  // Events NOT from the current session's plan are kept as-is: manual additions AND
  // shots from a PRIOR Auto-fill ("frozen"), so a fresh (e.g. windowed) Auto-fill
  // ADDS to the timeline rather than wiping it. New shots take orders after them.
  const kept = (prevEvents || []).filter((e) => !e.stepId || !planStepIds.has(e.stepId));
  const orderBase = kept.length ? Math.max(...kept.map((e) => e.order || 0)) + 1 : 0;

  const engine = plan
    .filter((s) => s.agent === 'animate')
    .map((step, i) => {
      const prev = prevByStep.get(step.id);
      // The keyframe = the picked still feeding this shot (its first resolved dep).
      const keyframeStep = (step.dependsOn || []).map((id) => stepById.get(id)).find((s) => s);
      const kf = pickedOutput(keyframeStep);
      const shot = pickedOutput(step);
      const shotUrl = shot && shot.kind === 'video' ? shot.url : '';
      const kfStatus = keyframeStep && keyframeStep.status;
      // "rendering" covers BOTH phases — keyframe being generated OR shot animating —
      // so a working clip never looks idle. "failed" if either step failed.
      const status = (step.status === 'failed' || kfStatus === 'failed') ? 'failed'
        : shotUrl ? 'shot'
          : (step.status === 'running' || kfStatus === 'running') ? 'rendering'
            : (kf && kf.url) ? 'keyframe'
              : 'empty';
      return timelineEvent({
        id: prev?.id,
        stepId: step.id,
        // Preserve a user reorder (prev.order); new shots slot after any frozen/manual.
        order: prev?.order != null ? prev.order : orderBase + i,
        beat: step.title || step.intent || prev?.beat || `Shot ${i + 1}`,
        durationSec: prev?.durationSec || Number(step.params?.duration) || DEFAULT_EVENT_SECONDS,
        keyframeUrl: (kf && kf.url) || prev?.keyframeUrl || '',
        shotUrl,
        bibleRefs: (keyframeStep && keyframeStep.bibleRefs) || step.bibleRefs || prev?.bibleRefs || [],
        status,
        locked: prev?.locked || !!step.locked,
        feedback: step.feedback || prev?.feedback || '',
        // Advisory QC for the shot = the keyframe step's QC (animate/video skips QC).
        qc: step.qc || (keyframeStep && keyframeStep.qc) || null,
      });
    });

  // Keep explicit orders (frozen/manual + new engine) so reorders survive; render sorts.
  return [...kept, ...engine];
};
